// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb8n8ztw4nKNS9cMu3dhpMJoMEKxZ5Ptg',
    appId: '1:321005862469:web:029b73ac4cd2df4d726d2c',
    messagingSenderId: '321005862469',
    projectId: 'xpressatec-8bcd1',
    authDomain: 'xpressatec-8bcd1.firebaseapp.com',
    storageBucket: 'xpressatec-8bcd1.firebasestorage.app',
    measurementId: 'G-ELWBPP9N4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_DUIVN20bjR9eYpwlp7m2WVfzEioSPt4',
    appId: '1:321005862469:android:ae4e7c2bf4fda191726d2c',
    messagingSenderId: '321005862469',
    projectId: 'xpressatec-8bcd1',
    storageBucket: 'xpressatec-8bcd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzZdmbrCM0CrR_mu7Jc1FFbuNRezcVbuk',
    appId: '1:321005862469:ios:3a44d57078a59b4a726d2c',
    messagingSenderId: '321005862469',
    projectId: 'xpressatec-8bcd1',
    storageBucket: 'xpressatec-8bcd1.firebasestorage.app',
    iosBundleId: 'com.example.xpressatec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzZdmbrCM0CrR_mu7Jc1FFbuNRezcVbuk',
    appId: '1:321005862469:ios:3a44d57078a59b4a726d2c',
    messagingSenderId: '321005862469',
    projectId: 'xpressatec-8bcd1',
    storageBucket: 'xpressatec-8bcd1.firebasestorage.app',
    iosBundleId: 'com.example.xpressatec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb8n8ztw4nKNS9cMu3dhpMJoMEKxZ5Ptg',
    appId: '1:321005862469:web:9337823ee0d4506f726d2c',
    messagingSenderId: '321005862469',
    projectId: 'xpressatec-8bcd1',
    authDomain: 'xpressatec-8bcd1.firebaseapp.com',
    storageBucket: 'xpressatec-8bcd1.firebasestorage.app',
    measurementId: 'G-4S2RMWTYY6',
  );
}
